### ISSUE TITLE
TypeError: Cannot read property 'disconnect' of undefined

### ISSUE THREAD

**Issue by sainikhit2k** [christiannwamba/realtime-chat-with-sentiment#3]
When i enter my name in text field and click enter the following error appears[](url)
<img width="1440" alt="Screenshot 2019-06-22 at 11 26 28 AM" src="https://user-images.githubusercontent.com/17419092/59960115-bf9f8b00-94e0-11e9-8daa-b41bdc75ded8.png">

**Comment by kris10cabrera** [comment]
I am having the same error @sainikhit2k. this is how I was able to fix it 
```
  componentWillUnmount() {
    if (this.pusher) {
      this.pusher.disconnect();
    }
  }
```
were you?

**Comment by cagansevencan** [comment]
All I see an empty white screen, it really didn't fix the issue...
